/*
 --------------------------
 Derived Class Destruction
 --------------------------
 - A child object is stored in memory as a parent object followed by the child
 part

    Shape *c = new Circle; //Create a Circle object in allocated memory
                           //Use the Circle object
    delete c;              //Release the memory - calls destructor(s)

- Which destructor(s) are called?

          Shape
      <------------>
      ...........................
      |            |            |
      '''''''''''''''''''''''''''
      <------------------------->
                 Circle
- the pointer will be to the start of this object. So if we call delete on this
pointer c, the Shape destructor is called and nothing from Circle. Why is that?

------------------------------
Virtual Destructor
------------------------------
- If the destructor is not trivial, static binding will be used

   Shape *c = new Circle;
   ...
   delete c; //Calls non-virtual ~Shape only

- We need to use dynamic binding. That is if they are virtual, use get dynamic
binding. If they are not virtual, we just get static binding. So in the static
binding case, the compiler sees pointer to Shape, so it puts in a call to the
Shape destructor only
- The destructor must be virtual

   Shape *c = new Circle;
   ....
   delete c; //calls ~Circle followed by ~Shape

- In the dynamic binding case, the run time knows that it is dealing with a
Circle object, so it calls the Circle destructor, and then the Shape destructor
gets called

---------------------------------
Synthesized Destructor
---------------------------------
- If we do not define a destructor, the compiler will synthesize one for us and
which does nothing. The point is that the default constructor is not virtual.
That was a decision that was taken a very long time ago in C++. The reason is
that having a virtual member function has a small amount of overhead. And if
your class is not supposed to be a base class, then that overhead is wasted. One
of the design principles of C++ is there should be no avoidable overhead. Or as
Bjarne Stroustrup puts it "You should not have to pay for anything that you do
no eat". So the extra overhead of a virtual function is not required, unless you
have a base class. And if you have a base class, then you can put it there
yourself which is all good. But this can give us a problem, if we are deleting
through pointer to base
- The default destructor generated by the compiler is NOT virtual
- If we are going through a pointer to base, this means that the derived part
of the object is not destroyed
  * Meory leak
  * Resource leaks
  * Undefined behavior

-------------------
Virtual Destructor
-------------------
- We can prevent this by implementing a destructor and making it virtual

   virtual ~Shape(){}           //Empty virtual destructor (all C++)
    virtual ~Shape = default;   //Default virtual destructor (C++11)

- We do not need to implement the other special member functions
- In general, if a class has virtual functions, it should have a virtual
destructor
 */

#include <iostream>
#include <vector>

using namespace std;

namespace without_virtual_destructor {
class Shape {
public:
  virtual void draw() const { cout << "Drawing a generic shape...\n"; }
  ~Shape() { cout << "Goodbye from Shape object!\n"; };
};

class Circle : public Shape {
public:
  // since dra() in Base class is declared as virtual and const, the next one
  // will be overriden and this one is an overload and overridden virtual
  // dispatch function
  void draw() { cout << "Drawing a circle...\n"; }                // overload
  void draw() const override { cout << "Drawing a circle...\n"; } // overridden
  ~Circle() { cout << "Goodbye from Circle object\n"; }
};

void example() {

  vector<Shape *> shapes; // vector of pointers to shape objects

  // create a pointer to a child class of Shape and append it to the vector
  shapes.push_back(new Circle());

  for (auto shape : shapes) {
    shape->draw(); // calls Circle::draw()
  }

  for (auto shape : shapes) {
    delete shape;
  }
}
} // namespace without_virtual_destructor

namespace with_virtual_destructor {
class Shape {
public:
  virtual void draw() const { cout << "Drawing a generic shape...\n"; }
  virtual ~Shape() { cout << "Goodbye from Shape object!\n"; };
};

class Circle : public Shape {
public:
  void draw() const override { cout << "Drawing a circle...\n"; }
  ~Circle() { cout << "Goodbye from Circle object\n"; }
};

void example() {

  vector<Shape *> shapes; // vector of pointers to shape objects

  // create a pointer to a child class of Shape and append it to the vector
  shapes.push_back(new Circle());

  for (auto shape : shapes) {
    shape->draw(); // calls Circle::draw()
  }

  for (auto shape : shapes) {
    delete shape;
  }
}
} // namespace with_virtual_destructor

int main() {

  without_virtual_destructor::example();
  cout << "\n---------with virtual destructor--------\n";
  with_virtual_destructor::example();
}
